# A conda environment for CSDMS Ivy lessons.
#
# Usage:
#   $ conda env create --file=environment.yaml
#   $ source activate ivy

name: ivy
channels:
  - conda-forge
dependencies:
  - python =3
  - pip
  - numpy
  - scipy
  - pandas
  - notebook
  - rasterio
  - pytest
  - coverage
  - bmipy
  # - bmi-example-python
  - pymt >=1.3
  - landlab >=2.5
  - terrainbento
  - pymt_child
  - pymt_hydrotrend
  - pymt_sedflux
  - bmi-topography
  - imageio
  - tqdm
  - jupytext
  - pre-commit
